### ISSUE TITLE
Mods Refuse to Deploy on Windows 11

### ISSUE THREAD

**Issue by KaiserCalm** [atampy25/simple-mod-framework#179]
![Screenshot from 2022-05-26 10-50-53](https://user-images.githubusercontent.com/81613945/170476428-fc707961-cc77-4326-82ef-eb9586fce38b.png)

I've tried different mods too the error seems to be similar, I also tried reinstalling the mod manager multiple times, but the error seems to persist.

My error ID is fb75ed88-8613-44ec-9c27-c1e7e6f63195

I can provide more information if need be.

Thank you for your time.

**Comment by hitman-resources** [comment]
There seems to be something of an ephemeral issue with random lines as the error; version 2.0.0 is currently being developed - it seems to solve the issue.

**Comment by KaiserCalm** [comment]
Thank you for the information!

**Comment by KaiserCalm** [comment]
Should I leave this issue open until then?

**Comment by TheBoxyBear** [comment]
If it's an issue with 1.5.6, which version should I fall back to if I want game pass support?

**Comment by RDIL** [comment]
As far as I'm aware, if you want to use the framework on the new patch, you have to use the latest version.

**Comment by atampy25** [comment]
Version 2.0.0 has been released!
