### ISSUE TITLE
Relicense to LGPLv3

### ISSUE THREAD

**Issue by atampy25** [atampy25/simple-mod-framework#268]
Going to relicense to LGPLv3

- [x] Consent from @AnthonyFuller 
- [x] Consent from @Notexe

**Comment by AnthonyFuller** [comment]
I, Anthony Fuller hereby grant permission to re-license Simple Mod Framework under the Lesser GNU Public License v3.

A portion of the commits made by AnthonyFuller are copyright of Anthony Fuller.
And I hereby grant the Simple Mod Framework project team to re-license Simple Mod Framework,
including all past, present and future contributions of the author listed above.

**Comment by Notexe** [comment]
I, Notexe hereby grant permission to re-license Simple Mod Framework under the GNU Public License v3 or the Lesser GNU Public License v3.

A portion of the commits made by Notexe are copyright of Notexe.
And I hereby grant the Simple Mod Framework project team to re-license Simple Mod Framework,
including all past, present and future contributions of the author listed above.

**Comment by atampy25** [comment]
Lmao
