### ISSUE TITLE
Cannot launch with latest version

### ISSUE THREAD

**Issue by TheBoxyBear** [atampy25/simple-mod-framework#389]
Using with the Windows Store version, launching Deploy.exe gives an error that thumbs.dat.decrypted.encrypted cannot be copied as thumbs.dat. Launching the executable as administrator causes it to close itself after the INFO lines are printed.

I can copy the file manually to the Runtime folder but it prompts be to escalate the action as administrator. I click Yes and it copies succesfully, however the app still tries to copy on startup, making it unusable. As a temporary workaround, where does the copy take place so I can make a fork with it removed?

**Comment by atampy25** [comment]
Try running the Load Order Manager as administrator

**Comment by TheBoxyBear** [comment]
Worked and can deploy mods
