### ISSUE TITLE
Use local resources instead of CDNs

### ISSUE THREAD

**Issue by YUCLing** [atampy25/simple-mod-framework#455]
Sometimes I'm experiencing some issues with connection to these CDN providers. As a result, the mod manager won't be loaded normally, and this is bad since the mod manager is a downloaded application.

It will be better if it can run without an Internet connection. :D

**Comment by bennett-sh** [comment]
I've implemented offline compatibility in my fork [SMF+](https://github.com/bennett-sh/simple-mod-framework-plus) in case you don't want to wait any longer. If you don't want to completely reinstall SMF, just copy the SMF+ ```Mod Manager```-folder into the existing ```Mod Manager```-folder and vice versa for uninstalling.
