### ISSUE TITLE
Skip intro option prevents the game from launching with Framework 2.2.2

### ISSUE THREAD

**Issue by TheBoxyBear** [atampy25/simple-mod-framework#461]
Using the Game Pass version 1.0.29.0 and Framework version 2.2.2.2, applying any mods suceeds but the game won't launch after going through the launcher or trying to start a benchmark is the game was modified while `skipIntro` is set to `true` in config.json which it is by default.

The issue persists after all mods are removed and can only be fixed by re-applying mods after disabling skipIntro or using the Verify and Repair feature in the Xbox app.

**Comment by atampy25** [comment]
This should properly have been fixed in 2.12.3.
