### ISSUE TITLE
Linux Version for Steam Deck someday?

### ISSUE THREAD

**Issue by IgLocoXD** [atampy25/simple-mod-framework#527]
Any plans to do a Steam Deck version? or information in how to compile it?

**Comment by atampy25** [comment]
There was a Linux fork maintained for some time by Notex, but it's since been discontinued. There are no current plans for a fork, because testing is already quite scarce and given I don't have a Linux install to work with it would largely be trial and error.

**Comment by iamPanka** [comment]
I tried to use it through Lutris and it's working, but I can't get to deploy one of the mods I use. I get this error https://hastebin.com/share/ohuyifaqir

**Comment by AnthonyFuller** [comment]
Using SMF on Linux is not a supported use case. The hope is that SMFv3 will work natively on Linux, but that is not in any way a guarantee.

Right now the recommended way to use mods on Linux is to use a Windows machine with the game, output SMF to a folder (it's in the config), and copy those over to the Linux machine.
