### ISSUE TITLE
modded game not launching

### ISSUE THREAD

**Issue by Moatmoat** [atampy25/simple-mod-framework#545]
When I attempt to launch the game with any combination of mods I get an error log that looks like this https://hastebin.com/share/lunorazufu, launching the mod manager with administrator privileges doesn't help any.

**Comment by atampy25** [comment]
This has been reported a couple times before but I've never been able to figure out how or why it could happen.

What are your OS specs (OS version, Home/Pro/etc, time the computer was made)?

**Comment by Moatmoat** [comment]
I have windows 10 home version 21h2 and originally built my computer 2019 but have upgraded parts of it since

**Comment by Moatmoat** [comment]
for some reason windows post an update and it fixed my problem
