### ISSUE TITLE
How to locally build the project

### ISSUE THREAD

**Issue by prolium** [atampy25/simple-mod-framework#568]
What I did:
1. Clone the repo (latest from `master`)
2. Made sure Node v18.x is in PATH env and properly recognized in terminal
3. npm install -g typescript
4. Then proceeded to follow the [Release Github Action](https://github.com/atampy25/simple-mod-framework/blob/main/.github/workflows/release.yml)
5. `npm install`
6. Then from admin powershell
```powershell
New-Item -ItemType Directory -Force -Path ./node_modules/piscina
robocopy ./piscina ./node_modules/piscina /COPYALL /E /is /it
```
7. `tsc`

This last step gives many errors, first the minified Three.js has something like this:
```javascript
O&&x=undefined
```
This throws an error because && has higher precedence than =, could be easily solved, but that means on your side you have a different setup or build system 
```javascript
O&&(x=undefined)
```
Once this is solved, many .ts files in `src\` are resulting in compilation errors.

I could build the sub-project `Mod Manager` just fine, but the server is not feasible.
How do you build this project ?

**Comment by atampy25** [comment]
TypeScript errors aren't real errors (technically the three.js one is but that file is from the original QuickEntity so its behaviour should be preserved); the vast majority of TS errors are just cases where dynamic typing is being used or where telling TypeScript that something is correct would be annoying and not particularly useful. The way I build the project is exactly the same as the action.
