### ISSUE TITLE
Getting error when applying the mods

### ISSUE THREAD

**Issue by vipulDessai** [atampy25/simple-mod-framework#572]
getting following error, when i press the apply button
```
Could not detect a workable game copy! If the game has recently updated, the framework will also need an update. If you're using a cracked version, that sounds like a you problem.
```

I'm using the xbox Hitman 3 game, the SFM while installing is able to detect the game folder and correctly copies the folder in the game directory, but when I launch the SFM and while applying the mod I get the above error, is there any workaround that I can try, please help

**Comment by atampy25** [comment]
> If the game has recently updated, the framework will also need an update.

#571 

cb386b9
