### ISSUE TITLE
Invalid folder names in cache

### ISSUE THREAD

**Issue by VoodooHillbilly** [atampy25/simple-mod-framework#573]
SMF is creating some invalid folder names starting with the Windows system reserved word `CON` followed by a period. As a result, the folders are inaccessible and require extra effort to delete. More info here: https://www.thewindowsclub.com/invalid-file-handle

The examples I've seen so far are:
`Custom Mission Pack\chunk1\Custom Mission Pack\chunk1\con.entity.json-7397b384671abfdd`
`Freelancer Variations\chunk26\con.entity.json-f0b2e28c5a1cf2ee`
`musicalmushr00m.LightingUltimate\chunk11\con.entity.json-95182ff594fd2ef6`

**Comment by atampy25** [comment]
This should be resolved by f34af0d.
