### ISSUE TITLE
Fetch mod requirements

### ISSUE THREAD

**Issue by bennett-sh** [atampy25/simple-mod-framework#578]
It would be great if you could add urls to the manifest from which SMF could download missing requirements.
Example of how the manifest could look after the change:
```json
{
  "requirements": [
    "SomeAuthor.SomeMod",
    {
      "id": "SomeAuthor.SomeModWithVersion",
      "version": "1.1.0"
    },
    {
      "id": "SomeAuthor.SomeModWithLatestDownload",
      "url": "https://github.com/myauthor/my-hm-lib/releases/latest/download/mod.framework.zip"
    },
    {
      "id": "SomeAuthor.SomeModWithFixedDownload",
      "url": "https://github.com/myauthor/my-hm-lib/releases/download/v1.0.0/mod.framework.zip"
    }
  ]
}
```

**Comment by atampy25** [comment]
This allows authors of mods unrelated to the required mod to specify arbitrary ZIPs as fulfilling the ID. If Hitmods is released, then the framework will likely attempt to find mods from there automatically when requirements aren't met, but otherwise this won't be added.
