### ISSUE TITLE
Refuses to download framework

### ISSUE THREAD

**Issue by tqoac** [atampy25/simple-mod-framework#585]
Launched the Simple Mod Framework Installer, it found my game folder (xbox version, on external drive), pressing the download button, it shows the spinning circle. and nothing, I've waited for about an hour and nothing has happened, I don't know if it's my internet or not, but it probably isn't.

**Comment by atampy25** [comment]
You can try downloading the latest release from here, but if no error has appeared in the installer then there's nothing I can really do since it means it's technically still downloading something.
