### ISSUE TITLE
SMF failing to deploy on Hitman version 3.160.0 

### ISSUE THREAD

**Issue by bravosixgoingdark** [atampy25/simple-mod-framework#632]
I have the Xbox Game Pass version of Hitman 3 and the game updated and SMF just refused to deploy citing that 

> Could not detect a workable game copy! If the game has recently updated, the framework will also need an update. If you're using a cracked version, that sounds like a you problem.

Likely that you would need to update the framework?

**Comment by AnthonyFuller** [comment]
> Hitman 3 and the game updated
> >If the game has recently updated, the framework will also need an update.

You have answered your own questions.
