### ISSUE TITLE
[Issue report] SMF 2.33.2 still doesn't work. (I'm sorry, atampy25)

### ISSUE THREAD

**Issue by eHollowHead** [atampy25/simple-mod-framework#674]
![image](https://github.com/atampy25/simple-mod-framework/assets/33979031/20675614-be75-4fe3-8fa0-c1929c014e31)
Latest SMF version, latest game version, completely reinstalled both. Everything was fine on Wednesday and Thursday, but my mods stopped working on Friday, so I attempted to update SMF (it didn't work out). Then I've deleted SMF folder, downloaded new version from GItHub, tried to install it and... well, the result was the same as you can see on pic above. After that, I've reinstalled the game, run it, the game worked. Tried to install SMF and... Well... Y'know... Pic above.

**Comment by eHollowHead** [comment]
P.S. The game isn't cracked, it's the latest steam version.

**Comment by atampy25** [comment]
Update is out
