### ISSUE TITLE
Deployment error (re: Issue #671) has reoccurred

### ISSUE THREAD

**Issue by redboy4796** [atampy25/simple-mod-framework#678]
Hello again, things were working for several days and after the latest Hitman update I started getting the same issue again. Until then, all the mods I normally use were all working fine except for Numbered Barcode, which I imagine would therefore be a mod-specific issue.

Anyway, I verified the files again to no avail, and I tried redownloading the Framework with no luck. I tried again after it had an update which I installed minutes ago.

I just tried the suggestion mentioned previously when this issue first arose of running rpkg-cli.exe in the third party folder, and it's come up with the following: "The code execution cannot proceed because VCOMP140.DLL was not found. Reinstalling the program may fix this problem."

Anyway, apologies for the further hassle, and thank you.

Redboy4796

**Comment by atampy25** [comment]
The error seems to suggest you're missing a Visual C++ redistributable that the RPKG tool requires. I have no idea which one the RPKG tool requires though - try [this one](https://aka.ms/vs/17/release/vc_redist.x64.exe).

**Comment by redboy4796** [comment]
Thanks, downloading it now and I shall report back soon

**Comment by redboy4796** [comment]
The setup was successful and rpkg-cli ran. I'm now going to test the mod manager again

**Comment by redboy4796** [comment]
It's deployed a mod, so it seems to be working. I will put the rest of my mod list back in and then I will report back, so far this seems to have solved it

**Comment by redboy4796** [comment]
Good news, it's all working now. I don't recall uninstalling any redistributables or anything and I thought I had them all, it's something I'm normally quite thorough with as they are prerequisites for a wide variety of applications. However somehow that's what was missing. Well anyway it's all sorted now! 

Thank you very much once again for your help Atampy! : )

**Comment by atampy25** [comment]
That's great! Glad to have helped.
