### ISSUE TITLE
WRONG FOLDER SELECTED WHEN INSTALLING THE SIMPLE MOD FRAMEWORK FOR HITMAN

### ISSUE THREAD

**Issue by Radoudouu** [atampy25/simple-mod-framework#700]
Hello, I'm using the Hitman World of Assasination with the gamepass ultimate on PC, the "Advanced management feature" is now a default option and is enabled, however it find the wrong folder, this one D:/WindowsApps/IOInteractive blablalbalba .... instead of D:/XboxGames/Hitman-PC or something, I tried install it with the wrong folder but nothing work i can't select any other folder

Any help is welcome and I thank any responses

(Also the link to report any issue did not works)

windows version : 10 pro N 22H2
hitman version : 3.170.1 (microsoft game pass)
Mod Framework used : Simple Mod Framework-200-2-32-3-1696317216.exe
![Capture](https://github.com/atampy25/simple-mod-framework/assets/155193793/0ab1a469-78f7-4e9c-ad5d-9455cd9bf029)

**Comment by JojjeE** [comment]
This is actually the correct path. The D:/XboxGames/PC - HITMAN 3 - Base Game/ path is actually a shortcut to D:\WindowsApps\IOInteractiveAS.PC-HITMAN3-BaseGame_1.0.37.0_x64__6h0y724g59e1w
Install SMF there, the installer knows what it's doing.

**Comment by Radoudouu** [comment]
FIXED : Install like the image, AND LAUNCH IN ADMIN ( windows key, right click to Simple Mod Framework, plus, and then launch in admin, or drag to your desktop to create a shortcut and then right click to Simple Mod Framework and launch in admin)
Thanks for your fast answer
