### ISSUE TITLE
Errors aren't being written to Deploy.log

### ISSUE THREAD

**Issue by VoodooHillbilly** [atampy25/simple-mod-framework#714]
When an error in deployment occurs, SMF's Mod Manager GUI displays the error message in that tiny "Applying your mods" popup. However, the errors are never written to `Deploy.log`. Running SMF 2.33.7 using any of these commands (or any earlier version with automatic logging):
`Mod Manager.cmd`
`Mod Manager\Mod Manager.exe`
`Deploy.exe`
`.\Deploy --logLevel verbose --logLevel debug --logLevel info --logLevel warn --logLevel error`
`.\Deploy --useConsoleLogging`
will all output this log when an error prevents deployment: [Deploy.log](https://github.com/atampy25/simple-mod-framework/files/14317334/Deploy.log)

I was expecting a log that includes error messages similar to this: [Deploy.log](https://github.com/atampy25/simple-mod-framework/files/14317335/Deploy.log)
It's more convenient for me than a button that uploads a log, since the Deploy.exe doesn't provide that option.

**Comment by atampy25** [comment]
This is unintentional, but known and not really fixable. The best practice is to give both Deploy.log and the uploaded link, which together provide all SMF logs at all levels, plus the error message and your config.

**Comment by VoodooHillbilly** [comment]
Well that's tedious.
