### ISSUE TITLE
Drag & Drop doesn't insert dropped mod

### ISSUE THREAD

**Issue by VoodooHillbilly** [atampy25/simple-mod-framework#715]
When trying to move a mod in the load order using drag & drop, SMF will only swap the positions of the original dragged mod and the mod it's been dropped nearest.

Following standard drag & drop functions, SMF should insert the dragged mod between the two mods it's been dropped nearest.

**Comment by atampy25** [comment]
This is intended behaviour for SMF v2 and will not be changed, but is already improved in v3.

**Comment by VoodooHillbilly** [comment]
That's the intended behavior? Why?

**Comment by atampy25** [comment]
SMF doesn't actually manage its drag and drop functionality, a Svelte component I didn't make does.

**Comment by VoodooHillbilly** [comment]
Oh that's unfortunate. Glad to hear it'll be improved in v3.
