### ISSUE TITLE
Anti-Piracy check is horrible

### ISSUE THREAD

**Issue by dogukans1** [atampy25/simple-mod-framework#746]
Checking whether the main game exe is altered or not is NOT a good way to check pirated versions of game. No piracy tool touches main executable files anymore, they simply alter Steam/Epic DLL's. What you should be doing is to check steam_api64.dll/EOSSDK-Win64-Shipping.dll as those handle DRM.

**Comment by AnthonyFuller** [comment]
You're right. It's not an anti-piracy check anyway. It's to stop people breaking their game installs.

**Comment by atampy25** [comment]
A good example of this is is how a non-updated SMF in the Ambrose Island update would have deleted critical game files if allowed to continue as normal without an update. The fact that a bunch of pirated versions modify the EXE (for who knows what reason) is incidental.
