### ISSUE TITLE
Fails to deploy

### ISSUE THREAD

**Issue by Trixiethepossum** [atampy25/simple-mod-framework#748]
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'startChild')
    at deploy (C:\snapshot\simple-mod-framework\compiled\deploy.js)
    at doTheThing (C:\snapshot\simple-mod-framework\compiled\main.js)

**Comment by atampy25** [comment]
Should be fixed in the latest update.

**Comment by Trixiethepossum** [comment]
> Should be fixed in the latest update.

just grabbed the update, same issue

https://hastebin.com/share/uweducafiv

[34mINFO[39m    Invalidating cache
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read properties of undefined (reading 'startChild')
    at deploy (C:\snapshot\simple-mod-framework\compiled\deploy.js)
    at doTheThing (C:\snapshot\simple-mod-framework\compiled\main.js)

**Comment by atampy25** [comment]
Try re-downloading the framework

**Comment by Trixiethepossum** [comment]
> Try re-downloading the framework

a  full wipe and reunpack fixed it, thanks for your help
